# Generated by Django 4.2.3 on 2023-07-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_data_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
